export const QUOTES = [
  "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.' — Lao Tzu",
  "The goal is to live a life you don't need a vacation from. — Rob Hill Sr",
  "Productivity is being able to do things that you were never able to do before. — Franz Kafka",
  "What is once well done is done forever. — Henry David Thoreau",
  "To do two things at once is to do neither. — Publilius Syrus",
  "The key is not to prioritize what's on your schedule, but to schedule your priorities. — Stephen Covey",
  "Lost time is never found again. — Benjamin Franklin",
  "Simplicity is the soul of efficiency. — Austin Freeman",
  "Action is the foundational key to all success. — Pablo Picasso",
  "The essence of self-discipline is to do the important thing rather than the urgent thing. — Barry Werner",
  "Planning is bringing the future into the present so that you can do something about it now. — Alan Lakein",
  "The secret of getting ahead is getting started. — Mark Twain",
  "My goal is no longer to get more done, but rather to have less to do. — Francine Jay",
  "Efficiency is doing things right; effectiveness is doing the right things. — Peter Drucker",
  "You may delay, but time will not. — Benjamin Franklin",
  "He who is not courageous enough to take risks will accomplish nothing in life. — Muhammad Ali",
  "Don't count the days, make the days count. — Muhammad Ali",
  "Ordinary people think merely of spending time, great people think of using it. — Arthur Schopenhauer",
  "Focus on being productive instead of busy. — Tim Ferriss",
  "The shortest answer is doing. — Lord Herbert",
  "Life is what happens when you're busy making other plans. — John Lennon",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work. — Stephen King",
  "A year from now you may wish you had started today. — Karen Lamb",
  "Position yourself to succeed by out-preparing everyone else. — Unknown",
  "Either you run the day or the day runs you. — Jim Rohn",
  "Your direction is more important than your speed. — Richard L. Evans",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "Do the hard jobs first. The easy jobs will take care of themselves. — Dale Carnegie",
  "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
  "Success is the sum of small efforts, repeated day-in and day-out. — Robert Collier",
  "It is not enough to be busy. So are the ants. The question is: What are we busy about? — Henry David Thoreau",
  "Spring is nature's way of saying, 'Let's party!' — Robin Williams",
  "And so the spring buds burst, and so I hope. — Unknown",
  "Every flower is a soul blossoming in nature. — Gerard De Nerval",
  "In the middle of every difficulty lies opportunity. — Albert Einstein",
  "If you want to live a happy life, tie it to a goal, not to people or things. — Albert Einstein",
  "Tough times never last, but tough people do. — Robert H. Schuller",
  "There are no shortcuts to any place worth going. — Beverly Sills",
  "Small deeds done are better than great deeds planned. — Peter Marshall",
  "The future depends on what you do today. — Mahatma Gandhi",
  "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus. — Alexander Graham Bell",
  "Continuous improvement is better than delayed perfection. — Mark Twain",
  "Change your thoughts and you change your world. — Norman Vincent Peale",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "Don't wait. The time will never be just right. — Napoleon Hill",
  "Perfection is not attainable, but if we chase perfection we can catch excellence. — Vince Lombardi",
  "Whatever you are, be a good one. — Abraham Lincoln",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "Success is not final; failure is not fatal: It is the courage to continue that counts. — Winston Churchill"
];
